### ISSUE TITLE
Morning Section Code Review | Week 5

### ISSUE THREAD

**Issue by huseyinbiyik** [nedjwab/E-ticket-Capstone#3]
This is a fantastic concert page, built well and functioning properly! But it needs some slight changes:

- Optional: as we all know, paid fonts create problems, you can save them in a font folder and let the users' computer download them automatically.
- <img width="1113" alt="Screen Shot 2022-04-15 at 10 08 41" src="https://user-images.githubusercontent.com/25887253/163539380-41292b21-afcc-453c-934b-fb5f8e0247da.png">
- That would be fantastic if program section cards are not flickering. So all they need is `border: 1px solid transparent;`
- According to the design, I guess the mobile navigation bar should be transparent and have no logo.
- According to the design, partner logos on the about page should be muted.(B&W)
- Optional: in terms of UX and security, menu links should not be opened on the new tab.

**Comment by MuhmmdUsama** [comment]
**Hi @nedjwab ,**

Your project is complete! There is nothing else to say ...  :shipit:

**Congratulations**! 🎉

Cheers and Happy coding!👏👏👏

**Comment by KanoCode** [comment]
Hi @nedjwab ,
Your project is complete, keep up the good work
congratulations! :fireworks: 
happy coding :partying_face:
